name: Main workflow
on:
  push:
    branches: [ master ]
    
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    name: Build and push the docker image
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker image
        run: |
          echo ${{ secrets.REGISTRY_TOKEN }} | docker login ghcr.io -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
          docker build -t ghcr.io/istartedanewsideprojectagain/s3rpacl-api .
          docker push ghcr.io/istartedanewsideprojectagain/s3rpacl-api